name: Despliegue en GitHub Pages con Sustitución de Clave API

on:
  push:
    branches:
      - main # Asegúrate que esta sea tu rama principal (o 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # PERMISOS: IMPRESCINDIBLE para que el Token pueda modificar la página
    permissions:
      contents: read
      pages: write
      id-token: write # Esto soluciona el error de permisos de despliegue

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 1. SUSTITUIR EL PLACEHOLDER CON EL VALOR REAL DEL SECRETO (Usando 'sed' de Linux)
      - name: Sustituir clave API en index.html
        env:
          GEMINI_API_KEY_SECURE: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # 1. Asegurarse de que el archivo index.html sea mutable
          chmod +w index.html
          
          # 2. Reemplazar la cadena literal REEMPLAZAR_CON_GEMINI_SECRET 
          # con el valor de la variable de entorno.
          sed -i 's|REEMPLAZAR_CON_GEMINI_SECRET|'${GEMINI_API_KEY_SECURE}'|g' index.html
          
          # Verificación (Muestra el valor inyectado en el log)
          echo "Verificación de la sustitución (Debe mostrar la clave oculta):"
          grep "const apiKey" index.html

      # 2. Configurar el entorno de despliegue
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      # 3. Cargar los archivos listos para el despliegue
      - name: Cargar artefactos de despliegue
        uses: actions/upload-pages-artifact@v3
        with:
          path: './' # Carga todos los archivos de la raíz

      # 4. Desplegar en GitHub Pages
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4